//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManager {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaskManager.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        internal static string CreateTaskPopupCancelButton {
            get {
                return ResourceManager.GetString("CreateTaskPopupCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create.
        /// </summary>
        internal static string CreateTaskPopupCreateButton {
            get {
                return ResourceManager.GetString("CreateTaskPopupCreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Task name.
        /// </summary>
        internal static string CreateTaskPopupLabel {
            get {
                return ResourceManager.GetString("CreateTaskPopupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3 Columns.
        /// </summary>
        internal static string CreateTaskPopupThreeColumnsButton {
            get {
                return ResourceManager.GetString("CreateTaskPopupThreeColumnsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2 Columns.
        /// </summary>
        internal static string CreateTaskPopupTwoColumnsButton {
            get {
                return ResourceManager.GetString("CreateTaskPopupTwoColumnsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        internal static string CreateTextItemPopupCancelButton {
            get {
                return ResourceManager.GetString("CreateTextItemPopupCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create.
        /// </summary>
        internal static string CreateTextItemPopupCreateButton {
            get {
                return ResourceManager.GetString("CreateTextItemPopupCreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter text:.
        /// </summary>
        internal static string CreateTextItemPopupLabel {
            get {
                return ResourceManager.GetString("CreateTextItemPopupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Between words.
        /// </summary>
        internal static string CreateTextItemPopupLabelTrimBetween {
            get {
                return ResourceManager.GetString("CreateTextItemPopupLabelTrimBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last.
        /// </summary>
        internal static string CreateTextItemPopupLabelTrimFinally {
            get {
                return ResourceManager.GetString("CreateTextItemPopupLabelTrimFinally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Trim first.
        /// </summary>
        internal static string CreateTextItemPopupLabelTrimFirst {
            get {
                return ResourceManager.GetString("CreateTextItemPopupLabelTrimFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Symbol.
        /// </summary>
        internal static string CreateTextItemPopupLabelTrimSymbol {
            get {
                return ResourceManager.GetString("CreateTextItemPopupLabelTrimSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Quick adding.
        /// </summary>
        internal static string CreateTextItemPopupQuickAddingLabel {
            get {
                return ResourceManager.GetString("CreateTextItemPopupQuickAddingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type.
        /// </summary>
        internal static string CreateTextItemPopupTypeLabel {
            get {
                return ResourceManager.GetString("CreateTextItemPopupTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        internal static string EditTextPopupSaveButton {
            get {
                return ResourceManager.GetString("EditTextPopupSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create.
        /// </summary>
        internal static string MainPageCreateTaskButton {
            get {
                return ResourceManager.GetString("MainPageCreateTaskButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        internal static string MainPageDeleteTaskButton {
            get {
                return ResourceManager.GetString("MainPageDeleteTaskButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open.
        /// </summary>
        internal static string MainPageOpenTaskButton {
            get {
                return ResourceManager.GetString("MainPageOpenTaskButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Properties.
        /// </summary>
        internal static string MainPagePropertiesButton {
            get {
                return ResourceManager.GetString("MainPagePropertiesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unselect.
        /// </summary>
        internal static string MainPageUnselectButton {
            get {
                return ResourceManager.GetString("MainPageUnselectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language:.
        /// </summary>
        internal static string SettingsPickerLanguageLabel {
            get {
                return ResourceManager.GetString("SettingsPickerLanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на English.
        /// </summary>
        internal static string SettingsPickerLanguageSelectedItem {
            get {
                return ResourceManager.GetString("SettingsPickerLanguageSelectedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose language:.
        /// </summary>
        internal static string SettingsPickerLanguageTitle {
            get {
                return ResourceManager.GetString("SettingsPickerLanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Quick move.
        /// </summary>
        internal static string SettingsQuickMoveLabel {
            get {
                return ResourceManager.GetString("SettingsQuickMoveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove all tasks.
        /// </summary>
        internal static string SettingsRemoveAllTasksButton {
            get {
                return ResourceManager.GetString("SettingsRemoveAllTasksButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save settings.
        /// </summary>
        internal static string SettingsSaveSettingsButton {
            get {
                return ResourceManager.GetString("SettingsSaveSettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Two columns settings.
        /// </summary>
        internal static string SettingsTwoColumnsSettingsLabel {
            get {
                return ResourceManager.GetString("SettingsTwoColumnsSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        internal static string ShellEditButton {
            get {
                return ResourceManager.GetString("ShellEditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tasks.
        /// </summary>
        internal static string ShellMainPageLabel {
            get {
                return ResourceManager.GetString("ShellMainPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        internal static string ShellSettingsLabel {
            get {
                return ResourceManager.GetString("ShellSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        internal static string ShellSettingsMenuLabel {
            get {
                return ResourceManager.GetString("ShellSettingsMenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tasks.
        /// </summary>
        internal static string ShellTasksMenuLabel {
            get {
                return ResourceManager.GetString("ShellTasksMenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add.
        /// </summary>
        internal static string TaskPageAddButton {
            get {
                return ResourceManager.GetString("TaskPageAddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        internal static string TaskPageDeleteButton {
            get {
                return ResourceManager.GetString("TaskPageDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Doing.
        /// </summary>
        internal static string TaskPageDoingLabel {
            get {
                return ResourceManager.GetString("TaskPageDoingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Done.
        /// </summary>
        internal static string TaskPageDoneLabel {
            get {
                return ResourceManager.GetString("TaskPageDoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        internal static string TaskPageEditButton {
            get {
                return ResourceManager.GetString("TaskPageEditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose type:.
        /// </summary>
        internal static string TaskPageItemPickerTitle {
            get {
                return ResourceManager.GetString("TaskPageItemPickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;-.
        /// </summary>
        internal static string TaskPageMoveLeftButton {
            get {
                return ResourceManager.GetString("TaskPageMoveLeftButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на -&gt;.
        /// </summary>
        internal static string TaskPageMoveRightButton {
            get {
                return ResourceManager.GetString("TaskPageMoveRightButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open.
        /// </summary>
        internal static string TaskPageOpenButton {
            get {
                return ResourceManager.GetString("TaskPageOpenButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To Do.
        /// </summary>
        internal static string TaskPageToDoLabel {
            get {
                return ResourceManager.GetString("TaskPageToDoLabel", resourceCulture);
            }
        }
    }
}
